<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Vault\Block\Customer\CreditCards $block */
$tokens = $block->getPaymentTokens();
?>
<?php if (count($tokens) !== 0) : ?>
    <div class="table-wrapper my-credit-cards col-xs-12 border border-1 rounded border-secondary bg-secondary-subtle p-4 my-5">
        <table class="data table table-credit-cards table-secondary" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Stored Payment Methods')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col card-number"><?= $block->escapeHtml(__('Card Number')) ?></th>
                <th scope="col" class="col expire"><?= $block->escapeHtml(__('Expiration Date')) ?></th>
                <th scope="col" class="col card-type"><?= $block->escapeHtml(__('Type')) ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($tokens as $token) {
                echo $block->renderTokenHtml($token);
            }
            ?>
            </tbody>
        </table>
    </div>

<?php elseif (!$block->isExistsCustomerTokens()) : ?>
    <div class="message info empty rounded"><span><?= $block->escapeHtml(__('You have no stored payment methods.')) ?></span></div>
<?php endif ?>
