<?php
$viewModel = $block->getData('view_model_consent');
$count = 0;
$consentPage = $viewModel->getConsentCheckboxData();
foreach ($consentPage as $consentdata) {
    $count++;
    if ($consentdata == $block->getLinkType()) {
        $consentdataVal = "Register";
        if ($consentdata == "contactpage") {
            $consentdataVal = "Contact";
        } elseif ($consentdata == "newsletterform") {
            $consentdataVal = "Subscribe";
        }
        ?>
        <div class="field sparsh_consent_checkbox required">
            <?php if ($escaper->escapeHtml($viewModel->getMsgContent())) { ?>
            <label class="label" for="comment"><?= $escaper->escapeHtml($viewModel->getMsgContent()); ?></label>
            <?php } ?>
            <div class="control">
                <input type="checkbox" id="<?= $escaper->escapeHtmlAttr('sparsh_consent_checkbox_' . $count) ?>"
                       name="sparsh_consent_checkbox"
                       data-validate="{required:true}" class="input-checkbox checkbox required" value="1">
                <label for="<?= $escaper->escapeHtmlAttr('sparsh_consent_checkbox_' . $count) ?>" class="label">
                    <?= $viewModel->getConsentContent(); ?>
                </label>
                <input type="hidden" name="gdpr_action" id="actiontype" value="<?= /* @noEscape */ $consentdataVal;?>">
            </div>
        </div>
        <script type="text/x-magento-init">
        {
            ".sparsh_consent_checkbox ": {
                "privacypolicyLink": {
                    "privacyLink": ".sparsh_consent_checkbox a",
                    "subscribeUrl": "#newsletter-validate-detail .subscribe"
                }
            }
        }
        </script>
        <?php
    }
}?>
