<!DOCTYPE html>
<html>
    <body>
        <div class="owl-carousel owl-carousel-images owl-theme">
            <div class="item">
                <img src="http://llupianez.magento.com/media/wysiwyg/mens/mens-pants.jpg" />
            </div>
            <div class="item">
                <img src="http://llupianez.magento.com/media/wysiwyg/gear/gear-equipment.jpg" />
            </div>
            <div class="item">
                <img src="http://llupianez.magento.com/media/wysiwyg/gear/gear-fitnes.jpg" />
            </div>
            <div class="item">
                <img src="http://llupianez.magento.com/media/wysiwyg/sale/sale-gear.jpg" />
            </div>
            <div class="item">
                <img src="http://llupianez.magento.com/media/wysiwyg/sale/sale-mens.jpg" />
            </div>
            <div class="item">
                <img src="http://llupianez.magento.com/media/wysiwyg/womens/womens-pants.jpg" />
            </div>
        </div>
    </body>
</html>